### ISSUE TITLE
Overlay component:  You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

### ISSUE THREAD

**Issue by Blackbaud-KrisMahon** [blackbaud/skyux-core#185]
### Expected behavior
Should not error and crash SPA.

### Actual behavior
After upgrading `@skyux/core` ~from 3.12.1 to 3.15.0~ to SKYUX 4, we've started seeing the following issue in our logs.  It appears to be happening on a page that displays a list with filters and various forms (so a lot of different SKYUX components are in play here).

```
TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
     at c (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.0073d635dbbe752447d0.chunk.7c77c169ab152d7da383c29fb2f00e40.js:978:2207)
     at o (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.0073d635dbbe752447d0.chunk.7c77c169ab152d7da383c29fb2f00e40.js:1941:4350)
     at e.call (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.0073d635dbbe752447d0.chunk.7c77c169ab152d7da383c29fb2f00e40.js:1791:11044)
     at e.subscribe (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.0073d635dbbe752447d0.chunk.7c77c169ab152d7da383c29fb2f00e40.js:52:2163)
     at e.addBackdropClickListener (https://sky.blackbaudcdn.net/skyuxapps/participant/skyux.5517e3616daa3ce69868.chunk.caa4b305e4c031e96c936900dd3a9533.js:1:484461)
     at https://sky.blackbaudcdn.net/skyuxapps/participant/skyux.5517e3616daa3ce69868.chunk.caa4b305e4c031e96c936900dd3a9533.js:1:483485
     at t.invokeTask (https://sky.blackbaudcdn.net/skyuxapps/participant/pollyfill.189a852b860db872d847.chunk.8b2286385702077c14a3e299925791a4.js:8:7690)
     at Object.onInvokeTask (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.0073d635dbbe752447d0.chunk.7c77c169ab152d7da383c29fb2f00e40.js:708:999)
     at t.invokeTask (https://sky.blackbaudcdn.net/skyuxapps/participant/pollyfill.189a852b860db872d847.chunk.8b2286385702077c14a3e299925791a4.js:8:7611)
     at e.runTask (https://sky.blackbaudcdn.net/skyuxapps/participant/pollyfill.189a852b860db872d847.chunk.8b2286385702077c14a3e299925791a4.js:8:2868)
```

According to the stacktrace, it appears this is coming from `SkyOverlayComponent.addBackdropClickListener()` since that is the only place that I can find a reference to that function name.

https://github.com/blackbaud/skyux-core/blob/3af7f07a4141d036696855782f403fd8e41031f3/src/app/public/modules/overlay/overlay.component.ts#L174

### Steps to reproduce
Upgrade to `@skyux/core` ~v3.15.0~ v4.3.0

### Severity
High

### Impact
High - It doesn't seem to happen every time, but in one week since upgrading, we've seen 10 different clients hit this issue numerous times across basically every major browser.  **This is causing the SPA to crash for those users.**

[AB#1584908](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1584908)

**Comment by Blackbaud-DanMiller** [comment]
@Blackbaud-KrisMahon can you send us any more information you have on these? Client bugs? Has anyone reproduced it in-house?

Any other information you have about the affected clients including browser specifics from instrumentation, or any info about extensions that may be being used?

Do you know the context of the error, or what component is being used that is triggering this?

**Comment by Blackbaud-KrisMahon** [comment]
We've upgraded our SPA to SKYUX 4 and are still seeing this issue intermittently from client logs.  Here is a current stack trace:

```
TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at l (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.118a9a7369aab1fedf6b.chunk.8856e5fe7e8c5a07ef2addf377382737.js:416:2269)
    at c (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.118a9a7369aab1fedf6b.chunk.8856e5fe7e8c5a07ef2addf377382737.js:2186:2763)
    at e.call (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.118a9a7369aab1fedf6b.chunk.8856e5fe7e8c5a07ef2addf377382737.js:2118:7655)
    at e.subscribe (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.118a9a7369aab1fedf6b.chunk.8856e5fe7e8c5a07ef2addf377382737.js:80:2886)
    at e.addBackdropClickListener (https://sky.blackbaudcdn.net/skyuxapps/participant/skyux.5ecfee05fdc88eac0c08.chunk.33e1cdcaf02cb9fc65247f07f54295d9.js:1:1231807)
    at https://sky.blackbaudcdn.net/skyuxapps/participant/skyux.5ecfee05fdc88eac0c08.chunk.33e1cdcaf02cb9fc65247f07f54295d9.js:1:1230825
    at t.invokeTask (https://sky.blackbaudcdn.net/skyuxapps/participant/pollyfill.4a9ad95d9e7887d412ff.chunk.192e6c38bd87ec629c102b128f513f0b.js:13:7859)
    at Object.onInvokeTask (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.118a9a7369aab1fedf6b.chunk.8856e5fe7e8c5a07ef2addf377382737.js:1634:1594)
    at t.invokeTask (https://sky.blackbaudcdn.net/skyuxapps/participant/pollyfill.4a9ad95d9e7887d412ff.chunk.192e6c38bd87ec629c102b128f513f0b.js:13:7780)
    at e.runTask (https://sky.blackbaudcdn.net/skyuxapps/participant/pollyfill.4a9ad95d9e7887d412ff.chunk.192e6c38bd87ec629c102b128f513f0b.js:13:2934)
```

Based on the method/code below, I think somehow it is ending up with an `undefined` stream.  I don't know what this code is for, so I can't really say how clients might be hitting it.  It could be a timing issue related to the `ngOnDestroy` code that sets a few things to `undefined`. and this method doesn't protect against possible `undefined` scenarios.
https://github.com/blackbaud/skyux-core/blob/3af7f07a4141d036696855782f403fd8e41031f3/src/app/public/modules/overlay/overlay.component.ts#L174

**Comment by Blackbaud-KrisMahon** [comment]
We've upgraded to 4.3.2 with the above fix, and it was looking good for awhile, but then we started getting similar errors again.  I'm now seeing a slightly different error, but it appears to be coming from the same location as the fix you made in 4.3.2.  However, this time it is failing because `this._backdropClick` is getting set to `undefined`.  I suspect that `this._closed` will also have the same issue of being `undefined`.

I think we should probably just remove these two lines of code to prevent any of the observables from being `undefined`.
https://github.com/blackbaud/skyux-core/blob/2edcf8d9acdf6ab2986e2a8e02a7a6c1ff77d14c/src/app/public/modules/overlay/overlay.component.ts#L145

```
TypeError: Unable to get property 'next' of undefined or null reference
   at Anonymous function (https://sky.blackbaudcdn.net/skyuxapps/participant/skyux.96a7dfdce682c05e878e.chunk.849719caace96f7627c23687d7474670.js:1:1333353)
   at t.prototype.__tryOrUnsub (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.4c9b616ef1cd7cce760d.chunk.0762a6ea4d0e4a2cc27d7d7d6338f3ce.js:407:7455)
   at t.prototype.next (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.4c9b616ef1cd7cce760d.chunk.0762a6ea4d0e4a2cc27d7d7d6338f3ce.js:407:6597)
   at t.prototype._next (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.4c9b616ef1cd7cce760d.chunk.0762a6ea4d0e4a2cc27d7d7d6338f3ce.js:407:5661)
   at t.prototype.next (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.4c9b616ef1cd7cce760d.chunk.0762a6ea4d0e4a2cc27d7d7d6338f3ce.js:407:5328)
   at t.prototype._next (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.4c9b616ef1cd7cce760d.chunk.0762a6ea4d0e4a2cc27d7d7d6338f3ce.js:407:5661)
   at t.prototype.next (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.4c9b616ef1cd7cce760d.chunk.0762a6ea4d0e4a2cc27d7d7d6338f3ce.js:407:5328)
   at Anonymous function (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.4c9b616ef1cd7cce760d.chunk.0762a6ea4d0e4a2cc27d7d7d6338f3ce.js:2024:1960)
   at t.prototype.invokeTask (https://sky.blackbaudcdn.net/skyuxapps/participant/pollyfill.4a9ad95d9e7887d412ff.chunk.192e6c38bd87ec629c102b128f513f0b.js:13:7735)
   at onInvokeTask (https://sky.blackbaudcdn.net/skyuxapps/participant/vendor.4c9b616ef1cd7cce760d.chunk.0762a6ea4d0e4a2cc27d7d7d6338f3ce.js:1641:1579)
```

**Comment by Blackbaud-AlexKingman** [comment]
Yep, looks like that's the same issue. Thanks for helping track it down. PR made!

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-KrisMahon `@skyux/core@4.3.3` now contains this fix. Let me know how it goes!
